name: 'greetings'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet the contributor'
        uses: garg3133/welcome-new-contributors@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Hey @${{ github.actor }}!, thank you for contributing to open source!🚀 Your pull request will be reviewed at the earliest.'
          issue-message: 'Hey @${{ github.actor }}!, thanks for dropping an issue. We will look into this as soon as possible.'
